name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    # Runs every hour, on the hour.
    # - cron: '0 * * * *'
    # Run every 5 minutes.
    # - cron: '*/5 * * * *'
    # At the beginning of every day.
    - cron: "0 0 * * *"
permissions:
  # To write the generated contents to the README.
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: lscr.io/linuxserver/code-server:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - name: Build the site in the jekyll/builder container
        run: |
          docker run -d \
            --name=code-server \
            -e PASSWORD=password \
            -e SUDO_PASSWORD=password \
            -e SUDO_PASSWORD_HASH= \
            -e PROXY_DOMAIN=localhost \
            -p 8443:8443 \
            lscr.io/linuxserver/code-server:latest
          
          
